const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('radar', {
  loadState: () => ipcRenderer.invoke('state:load'),
  saveState: (s) => ipcRenderer.invoke('state:save', s),
  run: (s) => ipcRenderer.invoke('run', s),
  stop: () => ipcRenderer.invoke('stop'),
  open: (url) => ipcRenderer.invoke('open', url),
  dataDir: () => ipcRenderer.invoke('datadir'),
  exportCsv: (results) => ipcRenderer.invoke('export:csv', results),
  exportSheet: (settings, results) => ipcRenderer.invoke('export:sheet', settings, results),
  reveal: (p) => ipcRenderer.invoke('reveal', p),
  listModels: (s) => ipcRenderer.invoke('models', s),
  suggestNiches: (s, ex) => ipcRenderer.invoke('niches:suggest', s, ex),
  suggestSources: (s, src) => ipcRenderer.invoke('suggest:sources', s, src),
  checkUpdate: (r) => ipcRenderer.invoke('update:check', r),
  version: () => ipcRenderer.invoke('version'),
  team: () => ipcRenderer.invoke('team'),
  trackList: () => ipcRenderer.invoke('track:list'),
  trackAdd: (e) => ipcRenderer.invoke('track:add', e),
  trackUpdate: (id, p) => ipcRenderer.invoke('track:update', id, p),
  trackRemove: (id) => ipcRenderer.invoke('track:remove', id),
  spend: () => ipcRenderer.invoke('spend'),
  learned: () => ipcRenderer.invoke('learned'),
  saveDebug: () => ipcRenderer.invoke('debug:save'),
  exportConfig: () => ipcRenderer.invoke('config:export'),
  importConfig: () => ipcRenderer.invoke('config:import'),
  onSuggestLog: (cb) => ipcRenderer.on('suggest:log', (_e, m, replace) => cb(m, replace)),
  stages: () => ipcRenderer.invoke('stages'),
  onStage: (cb) => ipcRenderer.on('run:stage', (_e, p) => cb(p)),
  onLog: (cb) => ipcRenderer.on('run:log', (_e, msg, replace) => cb(msg, replace))
});
